### ISSUE TITLE
Can't build on android

### ISSUE THREAD

**Issue by gintasz** [misaelriojasm/Multilanguage#1]
Getting this error when building for android:

```
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
Plugin project :shared_preferences_web not found. Please update settings.gradle.
Plugin project :shared_preferences_macos not found. Please update settings.gradle.

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':multilanguage' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1

```

may you update the kotlin version used in this dependency?

**Comment by misaelriojasm** [comment]
I think I was using the default by `flutter create`. You should not have problems with that compilation. Anyway I got a new version of this code with couple of features to make this easier may I will update this repo and the pub package I just got really busy into my current projects. 

Please let me know which is the status of this issue from your side. I will give a try as well a let you know below comments. thanks!

**Comment by misaelriojasm** [comment]
Hey friend, I've check the pub and it's working just fine. I need to clean this up absolutely. Many dummy code inside... meanwhile this is just working good. Let me know if you have a different issue to help with but yeah... I think you should update you project. I will close this issue. Remember this package depends with `shared_preferences`. you should take it too, thanks!
